language: c
sudo: false
git:
  depth: false
  quiet: true
env:
  global:
     - ARDUINO_IDE_VERSION="1.8.8"
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
install:
  - arduino --install-library "Adafruit TSL2561","FastLED","Adafruit Unified Sensor"
script:
  - arduino --board esp8266:esp8266:huzzah:eesz=4M3M,xtal=80 --save-prefs
  - rm $HOME/arduino_ide/libraries/Adafruit_Test_Library
  - mkdir LED_Sectional
  - cp *.ino *.h *.cpp LED_Sectional/
  - cd LED_Sectional
  - arduino --verify LED_Sectional.ino
notifications:
  email:
    on_success: change
    on_failure: change
