language: c
sudo: false
git:
  depth: false
  quiet: true
env:
  global:
     - ARDUINO_IDE_VERSION="1.8.8"
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
install:
  - arduino --install-library "Adafruit TSL2561","FastLED","Adafruit Unified Sensor"
script:
  - arduino --verify LED_Sectional.ino
notifications:
  email:
    on_success: change
    on_failure: change
